-- Auth data imported from the SvelteKit frontend's better-auth SQLite database.
--
-- Run once, after migration m036 has created the tables:
--   psql "$DATABASE_URL" -f 001_import_frontend_auth.sql
--
-- Idempotent (ON CONFLICT DO NOTHING), so re-running is safe.
--
-- Sessions and verifications are deliberately NOT imported. Sessions are
-- short-lived and cookie-scoped to the old origin, so everyone re-logs in
-- once; verification rows are expiring tokens with no value after cutover.
--
-- Password hashes come across as scrypt and keep working: they are verified
-- by DualFormatHasher (riven-api/src/server/legacy_password.rs), which is
-- pinned against a vector generated by the TypeScript library itself.
BEGIN;

-- 1 user(s)
INSERT INTO auth_users (id, name, email, email_verified, image, created_at, updated_at, username, display_username, role, banned, ban_reason, ban_expires) VALUES ('L3zZDJokCeLbOoRbpL6LUVTOmFO50C5X', 'oliverwalton', 'olivertgwalton03@gmail.com', false, NULL, '2026-05-15T09:11:18.476000+00:00', '2026-05-15T09:24:45.119000+00:00', 'oliverwalton', NULL, 'admin', false, NULL, NULL) ON CONFLICT (id) DO NOTHING;

-- 1 account(s)
INSERT INTO auth_accounts (id, account_id, provider_id, user_id, access_token, refresh_token, id_token, access_token_expires_at, refresh_token_expires_at, scope, password, created_at, updated_at) VALUES ('QY6l2EqgxTMEgkkIsBwpFeFetoiXJQNO', 'L3zZDJokCeLbOoRbpL6LUVTOmFO50C5X', 'credential', 'L3zZDJokCeLbOoRbpL6LUVTOmFO50C5X', NULL, NULL, NULL, NULL, NULL, NULL, 'ce22d5ab898ec39f5ce11aea911f7918:56402b12486c4ada440c90f3e0eccfd32c3e8f358bae930e1478cb6cee64f55e5acdf90f5497d238bfbcb7a2699526c53677500ce964f327731bd0c9df52933e', '2026-05-15T09:11:18.536000+00:00', '2026-05-15T09:11:18.536000+00:00') ON CONFLICT (id) DO NOTHING;

-- 0 passkey(s)

COMMIT;
