use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");

    let manifest = fs::read_to_string("Cargo.toml").expect("failed to read Cargo.toml");
    let plugin_crates = collect_plugin_crates(&manifest);
    let output = render_plugin_link_file(&plugin_crates);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let dest = out_dir.join("plugin_crates.rs");
    fs::write(dest, output).expect("failed to write generated plugin_crates.rs");
}

fn collect_plugin_crates(manifest: &str) -> Vec<String> {
    let mut in_dependencies = false;
    let mut plugin_crates = Vec::new();

    for line in manifest.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with('[') {
            in_dependencies = trimmed == "[dependencies]";
            continue;
        }

        if !in_dependencies || trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        let Some((name, _)) = trimmed.split_once('=') else {
            continue;
        };
        let name = name.trim();
        if name.starts_with("plugin-") {
            plugin_crates.push(name.replace('-', "_"));
        }
    }

    plugin_crates.sort();
    plugin_crates
}

fn render_plugin_link_file(plugin_crates: &[String]) -> String {
    if plugin_crates.is_empty() {
        return String::from("// no plugin crates discovered\n");
    }

    let mut output = String::from("// @generated by build.rs\n");
    for plugin_crate in plugin_crates {
        output.push_str("extern crate ");
        output.push_str(plugin_crate);
        output.push_str(";\n");
    }
    output
}

#[cfg(test)]
mod tests {
    use super::{collect_plugin_crates, render_plugin_link_file};

    #[test]
    fn collects_only_plugin_dependencies_from_manifest() {
        let manifest = r#"
[package]
name = "riven-app"

[dependencies]
riven-core = { path = "../riven-core" }
plugin-tmdb = { path = "../plugin-tmdb" }
plugin-seerr = { path = "../plugin-seerr" }
tokio = { workspace = true }

[build-dependencies]
cc = "1"
"#;

        let plugin_crates = collect_plugin_crates(manifest);

        assert_eq!(
            plugin_crates,
            vec!["plugin_seerr".to_string(), "plugin_tmdb".to_string()]
        );
    }

    #[test]
    fn renders_extern_crate_list() {
        let output =
            render_plugin_link_file(&["plugin_calendar".to_string(), "plugin_tmdb".to_string()]);

        assert!(output.contains("extern crate plugin_calendar;"));
        assert!(output.contains("extern crate plugin_tmdb;"));
    }
}
