//! Password hashing that understands both the TypeScript frontend's hashes and
//! better-auth-rs's own.
//!
//! The frontend's better-auth hashes with **scrypt**; better-auth-rs hashes with
//! **Argon2**. Without this, every existing user is locked out the moment auth
//! moves into riven, because their stored hash would never verify.
//!
//! So [`DualFormatHasher::verify`] accepts either format, and
//! [`DualFormatHasher::hash`] always writes Argon2 — new and changed passwords
//! are Argon2, old ones keep working, and the scrypt hashes drain away naturally
//! as people change passwords.
//!
//! # Why a verified scrypt hash is rewritten
//!
//! Dual-format verification only covers the code paths that use *this* hasher.
//! Several better-auth plugins verify against `verify_password(None, …)` — the
//! library's built-in Argon2 — no matter what hasher the instance is configured
//! with. `/delete-user` is one: it asks for the account password, hands the
//! stored hash to Argon2's PHC parser, and a scrypt hash fails to parse, so the
//! confirmation dialog says "Invalid password" whatever you type.
//!
//! Riven cannot pass its hasher to those plugins, so instead it makes sure they
//! never meet a scrypt hash: the first sign-in that verifies one rewrites it as
//! Argon2, in the background, keyed on the hash's own value. Migrated accounts
//! therefore heal on their next login rather than staying half-usable until
//! their owner happens to change password.
//!
//! # scrypt parameters
//!
//! Taken from better-auth's `hashPassword`: N=16384, r=16, p=1, dkLen=64, salt
//! is 16 random bytes hex-encoded, and the stored form is `{salt_hex}:{key_hex}`.
//!
//! The parameter that is easy to get wrong: the scrypt salt is the **ASCII bytes
//! of the hex string**, not the 16 decoded bytes. `verifies_a_hash_produced_by
//! _the_typescript_library` pins that against a vector generated by better-auth
//! itself, so a wrong assumption here fails the test rather than the login.

use argon2::password_hash::{PasswordHash, SaltString, rand_core::OsRng};
use argon2::{Argon2, PasswordHasher as _, PasswordVerifier};
use async_trait::async_trait;
use better_auth::{AuthError, AuthResult};
use better_auth_core::PasswordHasher;
use chrono::Utc;
use riven_core::entities::auth::account;
use sea_orm::{ColumnTrait, DatabaseConnection, EntityTrait, QueryFilter, Set};
use subtle::ConstantTimeEq;
use unicode_normalization::UnicodeNormalization;

/// scrypt cost: better-auth uses N=2^14.
const SCRYPT_LOG_N: u8 = 14;
const SCRYPT_R: u32 = 16;
const SCRYPT_P: u32 = 1;
/// Derived key length in bytes, hence 128 hex characters in the stored hash.
const SCRYPT_DK_LEN: usize = 64;
/// 16 salt bytes, hex-encoded.
const SCRYPT_SALT_HEX_LEN: usize = 32;
const SCRYPT_KEY_HEX_LEN: usize = SCRYPT_DK_LEN * 2;

pub struct DualFormatHasher {
    /// Where a verified scrypt hash is rewritten as Argon2. `None` disables the
    /// rewrite, which is how the hashing tests below run without a database.
    db: Option<DatabaseConnection>,
}

impl DualFormatHasher {
    pub fn new(db: DatabaseConnection) -> Self {
        Self { db: Some(db) }
    }

    /// Verification only — a verified legacy hash stays as it is.
    #[cfg(test)]
    fn offline() -> Self {
        Self { db: None }
    }

    /// Replace a scrypt hash with an Argon2 one, off the request's critical
    /// path: the caller is mid-sign-in and the rewrite is an optimisation, not
    /// part of the answer.
    ///
    /// The row is found by the hash itself rather than by user id, which
    /// `verify` is not given. Salts are 16 random bytes, so the value
    /// identifies one account; and matching on it is what makes the update
    /// safe to race against a password change writing the same column — that
    /// write replaces the value this one is looking for, so it simply matches
    /// nothing.
    fn upgrade(&self, legacy_hash: String, password: String) {
        let Some(db) = self.db.clone() else {
            return;
        };

        tokio::spawn(async move {
            let hashed = off_executor(move || Self::hash_argon2(&password)).await;
            let hashed = match hashed {
                Ok(hashed) => hashed,
                Err(error) => {
                    tracing::warn!(%error, "could not re-hash a legacy password");
                    return;
                }
            };

            let updated = account::Entity::update_many()
                .set(account::ActiveModel {
                    password: Set(Some(hashed)),
                    updated_at: Set(Utc::now()),
                    ..Default::default()
                })
                .filter(account::Column::Password.eq(legacy_hash))
                .exec(&db)
                .await;

            match updated {
                Ok(result) if result.rows_affected > 0 => {
                    tracing::info!("upgraded a scrypt password hash to argon2");
                }
                Ok(_) => {}
                Err(error) => tracing::warn!(%error, "could not store a re-hashed password"),
            }
        });
    }
    /// Split a stored hash into `(salt_hex, key_hex)` if it has the shape the
    /// TypeScript library writes. Anything else — notably Argon2's `$argon2id$…`
    /// PHC string — returns `None` and falls through to Argon2.
    fn as_scrypt(hash: &str) -> Option<(&str, &str)> {
        let (salt, key) = hash.split_once(':')?;
        let well_formed = salt.len() == SCRYPT_SALT_HEX_LEN
            && key.len() == SCRYPT_KEY_HEX_LEN
            && salt.bytes().all(|b| b.is_ascii_hexdigit())
            && key.bytes().all(|b| b.is_ascii_hexdigit());
        well_formed.then_some((salt, key))
    }

    /// better-auth normalises to NFKC before hashing, so a password typed with
    /// composed vs decomposed accents verifies either way.
    fn normalize(password: &str) -> String {
        password.nfkc().collect()
    }

    fn verify_scrypt(salt_hex: &str, key_hex: &str, password: &str) -> AuthResult<bool> {
        // scrypt 0.12's `Params::new` takes only the cost parameters; the output
        // length is the length of the buffer passed to `scrypt`.
        let params = scrypt::Params::new(SCRYPT_LOG_N, SCRYPT_R, SCRYPT_P)
            .map_err(|error| AuthError::internal(format!("invalid scrypt parameters: {error}")))?;

        let expected = hex::decode(key_hex)
            .map_err(|error| AuthError::internal(format!("malformed scrypt hash: {error}")))?;

        let mut derived = [0_u8; SCRYPT_DK_LEN];
        scrypt::scrypt(
            Self::normalize(password).as_bytes(),
            // The hex string itself, not its decoded bytes — see module docs.
            salt_hex.as_bytes(),
            &params,
            &mut derived,
        )
        .map_err(|error| AuthError::internal(format!("scrypt failed: {error}")))?;

        Ok(derived.ct_eq(expected.as_slice()).into())
    }

    fn verify_argon2(hash: &str, password: &str) -> AuthResult<bool> {
        let parsed = PasswordHash::new(hash)
            .map_err(|error| AuthError::internal(format!("malformed argon2 hash: {error}")))?;
        Ok(Argon2::default()
            .verify_password(password.as_bytes(), &parsed)
            .is_ok())
    }

    fn hash_argon2(password: &str) -> AuthResult<String> {
        let salt = SaltString::generate(&mut OsRng);
        Argon2::default()
            .hash_password(password.as_bytes(), &salt)
            .map(|hash| hash.to_string())
            .map_err(|error| AuthError::internal(format!("failed to hash password: {error}")))
    }
}

/// Run one KDF off the async executor.
///
/// Both algorithms here are deliberately expensive — Argon2's defaults cost
/// ~19 MiB and two passes, and scrypt at `log_n = 14` is comparable — so running
/// them inline parks a runtime worker for the whole of every sign-in, and a
/// handful of concurrent attempts stalls unrelated request handling on the same
/// thread. The work is CPU-bound with no await points, which is exactly what
/// `spawn_blocking` is for.
async fn off_executor<T, F>(work: F) -> AuthResult<T>
where
    F: FnOnce() -> AuthResult<T> + Send + 'static,
    T: Send + 'static,
{
    tokio::task::spawn_blocking(work)
        .await
        .map_err(|error| AuthError::internal(format!("password hashing task failed: {error}")))?
}

#[async_trait]
impl PasswordHasher for DualFormatHasher {
    async fn hash(&self, password: &str) -> AuthResult<String> {
        let password = password.to_string();
        off_executor(move || Self::hash_argon2(&password)).await
    }

    async fn verify(&self, hash: &str, password: &str) -> AuthResult<bool> {
        let Some((salt_hex, key_hex)) = Self::as_scrypt(hash) else {
            let hash = hash.to_string();
            let password = password.to_string();
            return off_executor(move || Self::verify_argon2(&hash, &password)).await;
        };

        let (salt_hex, key_hex) = (salt_hex.to_string(), key_hex.to_string());
        let verified = {
            let password = password.to_string();
            off_executor(move || Self::verify_scrypt(&salt_hex, &key_hex, &password)).await?
        };

        // Only a hash that just proved itself is worth rewriting, and only the
        // password that proved it can produce the replacement.
        if verified {
            self.upgrade(hash.to_string(), password.to_string());
        }

        Ok(verified)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generated by the TypeScript `better-auth` package itself — the same
    /// version and code path that wrote the hashes now sitting in the frontend's
    /// SQLite. If this fails, existing users cannot log in.
    const TS_HASH: &str = "f75f61efb8db90adf62b0110c3112c29:bbf6b844a6a40007b1a7acb9d650db802601ad6dc5ffe63317a9ba1bf653475bdc10846af2f1228b672ea4ddf7c03b74ca77004a8893e9562d0a4cbdb3c4bf97";
    const TS_PASSWORD: &str = "correct horse battery staple";

    #[tokio::test]
    async fn verifies_a_hash_produced_by_the_typescript_library() {
        assert!(
            DualFormatHasher::offline()
                .verify(TS_HASH, TS_PASSWORD)
                .await
                .unwrap(),
            "scrypt parameters or salt encoding do not match better-auth"
        );
    }

    #[tokio::test]
    async fn rejects_a_wrong_password_against_the_typescript_hash() {
        assert!(
            !DualFormatHasher::offline()
                .verify(TS_HASH, "not the password")
                .await
                .unwrap()
        );
    }

    #[tokio::test]
    async fn round_trips_its_own_argon2_hashes() {
        let hash = DualFormatHasher::offline().hash("hunter2").await.unwrap();
        assert!(
            hash.starts_with("$argon2"),
            "expected PHC string, got {hash}"
        );
        assert!(
            DualFormatHasher::offline()
                .verify(&hash, "hunter2")
                .await
                .unwrap()
        );
        assert!(
            !DualFormatHasher::offline()
                .verify(&hash, "hunter3")
                .await
                .unwrap()
        );
    }

    #[test]
    fn only_well_formed_scrypt_hashes_take_the_scrypt_path() {
        assert!(DualFormatHasher::as_scrypt(TS_HASH).is_some());
        // Argon2 PHC strings contain `$`, not a bare `salt:key`.
        assert!(DualFormatHasher::as_scrypt("$argon2id$v=19$m=19456,t=2,p=1$abc$def").is_none());
        // Right shape, wrong lengths.
        assert!(DualFormatHasher::as_scrypt("abc:def").is_none());
        // Right lengths, non-hex.
        let not_hex = format!("{}:{}", "z".repeat(32), "z".repeat(128));
        assert!(DualFormatHasher::as_scrypt(&not_hex).is_none());
    }

    #[tokio::test]
    async fn nfkc_normalisation_matches_the_typescript_side() {
        // U+00E9 vs "e" + U+0301 normalise to the same NFKC form, so a password
        // typed either way must verify against one stored hash.
        let composed = "caf\u{00e9}";
        let decomposed = "cafe\u{0301}";
        let hash = DualFormatHasher::offline().hash(composed).await.unwrap();
        assert_eq!(
            DualFormatHasher::normalize(composed),
            DualFormatHasher::normalize(decomposed)
        );
        // Argon2 path does not normalise, so this documents the known gap:
        // only the scrypt path applies NFKC, matching better-auth's behaviour.
        assert!(
            DualFormatHasher::offline()
                .verify(&hash, composed)
                .await
                .unwrap()
        );
    }
}
