//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use crate::types::FileSystemEntryType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    async_graphql::SimpleObject,
)]
#[graphql(name = "FileSystemEntry", complex)]
#[sea_orm(table_name = "filesystem_entries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub file_size: i64,
    pub created_at: DateTimeUtc,
    pub updated_at: Option<DateTimeUtc>,
    pub media_item_id: i64,
    pub entry_type: FileSystemEntryType,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_filename: Option<String>,
    /// Resolved through the [`ComplexObject`] impl below rather than exposed
    /// directly — see `download_url` there for why.
    #[graphql(skip)]
    #[sea_orm(column_type = "Text", nullable)]
    pub download_url: Option<String>,
    #[graphql(skip)]
    #[sea_orm(column_type = "Text", nullable)]
    pub stream_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub plugin: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_download_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub library_profiles: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    /// The stored document. Read it through the typed `mediaMetadata` field.
    #[graphql(skip)]
    pub media_metadata: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub language: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_original_filename: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub subtitle_content: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_hash: Option<String>,
    pub video_file_size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub opensubtitles_id: Option<String>,
    pub stream_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resolution: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ranking_profile_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_provider: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub usenet_info_hash: Option<String>,
    pub usenet_file_index: Option<i32>,
}

#[async_graphql::ComplexObject]
impl Model {
    async fn download_url(&self, ctx: &async_graphql::Context<'_>) -> Option<&str> {
        self.credential(ctx, self.download_url.as_deref())
    }

    async fn stream_url(&self, ctx: &async_graphql::Context<'_>) -> Option<&str> {
        self.credential(ctx, self.stream_url.as_deref())
    }

    /// The stored document, typed. A row written by an older build that is
    /// missing fields still reads — every field defaults.
    async fn media_metadata(&self) -> Option<MediaMetadata> {
        serde_json::from_value(self.media_metadata.clone()?).ok()
    }
}

impl Model {
    /// `value` when the caller may act on releases, `None` otherwise.
    ///
    /// `ScrapeItems` is the threshold because it is already the capability that
    /// governs choosing and committing a release — anyone who holds it can
    /// obtain these URLs through the download flow anyway.
    fn credential<'a>(
        &self,
        ctx: &async_graphql::Context<'_>,
        value: Option<&'a str>,
    ) -> Option<&'a str> {
        let allowed = crate::auth::request_role(ctx)
            .is_ok_and(|role| crate::auth::Capability::ScrapeItems.granted_to(role));
        allowed.then_some(value).flatten()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::media_items::Entity",
        from = "Column::MediaItemId",
        to = "super::media_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaItems,
    #[sea_orm(
        belongs_to = "super::streams::Entity",
        from = "Column::StreamId",
        to = "super::streams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Streams,
}

impl Related<super::media_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItems.def()
    }
}

impl Related<super::streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Streams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn base_directory(&self) -> &str {
        if self.path.starts_with("/movies") {
            "movies"
        } else {
            "shows"
        }
    }

    pub fn vfs_filename(&self, pretty_name: &str) -> String {
        let ext = self
            .original_filename
            .as_ref()
            .and_then(|f| f.rsplit('.').next())
            .unwrap_or("mkv");
        format!("{pretty_name}.{ext}")
    }
}

/// The `media_metadata` document, derived from a release filename by
/// `riven_rank::derive_media_metadata` and stored as JSON on the entry.
///
/// It is typed here rather than handed over as a `JSON` scalar because both
/// clients used to re-parse the blob — the Swift app in `FileDetailsView` and
/// the web frontend in `lib/types/riven.ts` — each maintaining its own copy of
/// a shape only this repo defines.
#[derive(serde::Deserialize, async_graphql::SimpleObject, Default, Clone, Debug, PartialEq)]
#[serde(default)]
pub struct MediaMetadata {
    pub filename: Option<String>,
    pub original_filename: Option<String>,
    pub parsed_title: Option<String>,
    pub year: Option<i64>,
    pub video: Option<VideoMetadata>,
    pub audio_tracks: Vec<AudioTrack>,
    pub subtitle_tracks: Vec<SubtitleTrack>,
    pub quality_source: Option<String>,
    pub container_format: Vec<String>,
    pub bitrate: Option<i64>,
    pub duration: Option<f64>,
    pub is_remux: bool,
    pub is_proper: bool,
    pub is_repack: bool,
    /// `parsed` when derived from the filename; set by whoever wrote the row.
    pub data_source: Option<String>,
}

#[derive(serde::Deserialize, async_graphql::SimpleObject, Default, Clone, Debug, PartialEq)]
#[serde(default)]
pub struct VideoMetadata {
    pub codec: Option<String>,
    pub resolution_width: Option<i64>,
    pub resolution_height: Option<i64>,
    pub bit_depth: Option<i64>,
    pub hdr_type: Option<String>,
    pub frame_rate: Option<f64>,
}

#[derive(serde::Deserialize, async_graphql::SimpleObject, Default, Clone, Debug, PartialEq)]
#[serde(default)]
pub struct AudioTrack {
    pub codec: Option<String>,
    pub channels: Option<i64>,
    pub language: Option<String>,
}

#[derive(serde::Deserialize, async_graphql::SimpleObject, Default, Clone, Debug, PartialEq)]
#[serde(default)]
pub struct SubtitleTrack {
    pub codec: Option<String>,
    pub language: Option<String>,
}
