//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use crate::types::FileSystemEntryType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    async_graphql::SimpleObject,
)]
#[graphql(name = "FileSystemEntry")]
#[sea_orm(table_name = "filesystem_entries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub file_size: i64,
    pub created_at: DateTimeUtc,
    pub updated_at: Option<DateTimeUtc>,
    pub media_item_id: i64,
    pub entry_type: FileSystemEntryType,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub original_filename: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub download_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stream_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub plugin: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_download_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub library_profiles: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub media_metadata: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub language: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_original_filename: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub subtitle_content: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_hash: Option<String>,
    pub video_file_size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub opensubtitles_id: Option<String>,
    pub stream_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resolution: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ranking_profile_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_provider: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub usenet_info_hash: Option<String>,
    pub usenet_file_index: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::media_items::Entity",
        from = "Column::MediaItemId",
        to = "super::media_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaItems,
    #[sea_orm(
        belongs_to = "super::streams::Entity",
        from = "Column::StreamId",
        to = "super::streams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Streams,
}

impl Related<super::media_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItems.def()
    }
}

impl Related<super::streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Streams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn base_directory(&self) -> &str {
        if self.path.starts_with("/movies") {
            "movies"
        } else {
            "shows"
        }
    }

    pub fn vfs_filename(&self, pretty_name: &str) -> String {
        let ext = self
            .original_filename
            .as_ref()
            .and_then(|f| f.rsplit('.').next())
            .unwrap_or("mkv");
        format!("{pretty_name}.{ext}")
    }
}
