//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use crate::types::ItemRequestState;
use crate::types::ItemRequestType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    async_graphql::SimpleObject,
)]
#[graphql(name = "ItemRequest")]
#[sea_orm(table_name = "item_requests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub imdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub tmdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub tvdb_id: Option<String>,
    pub request_type: ItemRequestType,
    #[sea_orm(column_type = "Text", nullable)]
    pub requested_by: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub external_request_id: Option<String>,
    pub created_at: DateTimeUtc,
    pub completed_at: Option<DateTimeUtc>,
    pub state: ItemRequestState,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub seasons: Option<Json>,
    pub is_partial_request: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::media_items::Entity")]
    MediaItems,
}

impl Related<super::media_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
