//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use crate::entities::helpers::build_filesystem_metadata;
use crate::settings::FilesystemItemMetadata;
use crate::types::ContentRating;
use crate::types::MediaItemState;
use crate::types::MediaItemType;
use crate::types::ShowStatus;
use chrono::Datelike;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Serialize,
    Deserialize,
    async_graphql::SimpleObject,
)]
#[graphql(name = "MediaItem")]
#[sea_orm(table_name = "media_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub full_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub imdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub tvdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub tmdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub poster_path: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: Option<DateTimeUtc>,
    pub indexed_at: Option<DateTimeUtc>,
    pub scraped_at: Option<DateTimeUtc>,
    pub scraped_times: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub aliases: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub network: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub country: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub language: Option<String>,
    pub aired_at: Option<Date>,
    pub year: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub genres: Option<Json>,
    #[sea_orm(column_type = "Double", nullable)]
    pub rating: Option<f64>,
    pub content_rating: Option<ContentRating>,
    pub state: MediaItemState,
    pub failed_attempts: i32,
    pub item_type: MediaItemType,
    pub is_requested: bool,
    pub show_status: Option<ShowStatus>,
    pub season_number: Option<i32>,
    pub is_special: Option<bool>,
    pub parent_id: Option<i64>,
    pub episode_number: Option<i32>,
    pub absolute_number: Option<i32>,
    pub runtime: Option<i32>,
    pub item_request_id: Option<i64>,
    pub active_stream_id: Option<i64>,
    pub is_anime: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub network_timezone: Option<String>,
    pub aired_at_utc: Option<DateTimeUtc>,
    pub last_scrape_attempt_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::filesystem_entries::Entity")]
    FilesystemEntries,
    #[sea_orm(
        belongs_to = "super::item_requests::Entity",
        from = "Column::ItemRequestId",
        to = "super::item_requests::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemRequests,
    #[sea_orm(has_many = "super::media_item_blacklisted_streams::Entity")]
    MediaItemBlacklistedStreams,
    #[sea_orm(has_many = "super::media_item_streams::Entity")]
    MediaItemStreams,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::streams::Entity",
        from = "Column::ActiveStreamId",
        to = "super::streams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Streams,
    #[sea_orm(has_many = "super::usenet_file_health::Entity")]
    UsenetFileHealth,
}

impl Related<super::filesystem_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FilesystemEntries.def()
    }
}

impl Related<super::item_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemRequests.def()
    }
}

impl Related<super::media_item_blacklisted_streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItemBlacklistedStreams.def()
    }
}

impl Related<super::media_item_streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItemStreams.def()
    }
}

impl Related<super::streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Streams.def()
    }
}

impl Related<super::usenet_file_health::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsenetFileHealth.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn filesystem_metadata(&self) -> FilesystemItemMetadata {
        build_filesystem_metadata(
            self.genres.as_ref(),
            self.network.clone(),
            self.content_rating,
            self.language.clone(),
            self.country.clone(),
            self.aired_at.map(|date| date.year()).or(self.year),
            self.rating,
            self.is_anime,
        )
    }

    pub fn pretty_name(&self) -> String {
        let year_str = self.year.map(|y| format!(" ({y})")).unwrap_or_default();
        let id_str = match self.item_type {
            MediaItemType::Movie => self
                .tmdb_id
                .as_ref()
                .map(|id| format!(" {{tmdb-{id}}}"))
                .unwrap_or_default(),
            _ => self
                .tvdb_id
                .as_ref()
                .map(|id| format!(" {{tvdb-{id}}}"))
                .unwrap_or_default(),
        };
        format!("{}{year_str}{id_str}", self.title)
    }
}
