//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "media_item_blacklisted_streams")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub media_item_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub stream_id: i64,
    pub permanent: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::media_items::Entity",
        from = "Column::MediaItemId",
        to = "super::media_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaItems,
    #[sea_orm(
        belongs_to = "super::streams::Entity",
        from = "Column::StreamId",
        to = "super::streams::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Streams,
}

impl Related<super::media_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItems.def()
    }
}

impl Related<super::streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Streams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
