//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use crate::entities::helpers::build_filesystem_metadata;
use crate::settings::FilesystemItemMetadata;
use crate::types::ContentRating;
use crate::types::MediaItemState;
use crate::types::MediaItemType;
use crate::types::ShowStatus;
use chrono::Datelike;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, async_graphql::SimpleObject,
)]
#[graphql(name = "MediaItem", complex)]
#[sea_orm(table_name = "media_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub full_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub imdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub tvdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub tmdb_id: Option<String>,
    /// As the indexer stored it. Read it through the `posterPath` GraphQL
    /// field, which resolves it to a URL.
    #[graphql(skip)]
    #[sea_orm(column_type = "Text", nullable)]
    pub poster_path: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: Option<DateTimeUtc>,
    pub indexed_at: Option<DateTimeUtc>,
    pub scraped_at: Option<DateTimeUtc>,
    pub scraped_times: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub aliases: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub network: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub country: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub language: Option<String>,
    pub aired_at: Option<Date>,
    pub year: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub genres: Option<Json>,
    #[sea_orm(column_type = "Double", nullable)]
    pub rating: Option<f64>,
    pub content_rating: Option<ContentRating>,
    pub state: MediaItemState,
    pub failed_attempts: i32,
    pub item_type: MediaItemType,
    pub is_requested: bool,
    pub show_status: Option<ShowStatus>,
    pub season_number: Option<i32>,
    pub is_special: Option<bool>,
    pub parent_id: Option<i64>,
    pub episode_number: Option<i32>,
    pub absolute_number: Option<i32>,
    pub runtime: Option<i32>,
    pub item_request_id: Option<i64>,
    pub active_stream_id: Option<i64>,
    pub is_anime: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub network_timezone: Option<String>,
    pub aired_at_utc: Option<DateTimeUtc>,
    pub last_scrape_attempt_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::filesystem_entries::Entity")]
    FilesystemEntries,
    #[sea_orm(
        belongs_to = "super::item_requests::Entity",
        from = "Column::ItemRequestId",
        to = "super::item_requests::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemRequests,
    #[sea_orm(has_many = "super::media_item_blacklisted_streams::Entity")]
    MediaItemBlacklistedStreams,
    #[sea_orm(has_many = "super::media_item_streams::Entity")]
    MediaItemStreams,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::streams::Entity",
        from = "Column::ActiveStreamId",
        to = "super::streams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Streams,
    #[sea_orm(has_many = "super::usenet_file_health::Entity")]
    UsenetFileHealth,
}

impl Related<super::filesystem_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FilesystemEntries.def()
    }
}

impl Related<super::item_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemRequests.def()
    }
}

impl Related<super::media_item_blacklisted_streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItemBlacklistedStreams.def()
    }
}

impl Related<super::media_item_streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItemStreams.def()
    }
}

impl Related<super::streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Streams.def()
    }
}

impl Related<super::usenet_file_health::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsenetFileHealth.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn filesystem_metadata(&self) -> FilesystemItemMetadata {
        build_filesystem_metadata(
            self.genres.as_ref(),
            self.network.clone(),
            self.content_rating,
            self.language.clone(),
            self.country.clone(),
            self.aired_at.map(|date| date.year()).or(self.year),
            self.rating,
            self.is_anime,
        )
    }

    pub fn pretty_name(&self) -> String {
        let year_str = self.year.map(|y| format!(" ({y})")).unwrap_or_default();
        let id_str = match self.item_type {
            MediaItemType::Movie => self
                .tmdb_id
                .as_ref()
                .map(|id| format!(" {{tmdb-{id}}}"))
                .unwrap_or_default(),
            _ => self
                .tvdb_id
                .as_ref()
                .map(|id| format!(" {{tvdb-{id}}}"))
                .unwrap_or_default(),
        };
        format!("{}{year_str}{id_str}", self.title)
    }
}

#[async_graphql::ComplexObject]
impl Model {
    /// Absolute artwork URL. The column holds a bare path for anything indexed
    /// before the plugins normalised what they wrote, so it is resolved here
    /// rather than in each client.
    async fn poster_path(&self) -> Option<String> {
        crate::entities::helpers::artwork_url(
            self.poster_path.as_deref(),
            crate::entities::helpers::Artwork::Poster,
        )
    }

    /// Who is responsible for this item existing, for display next to other
    /// item metadata. `None` for anything with no linked request at all — a
    /// list-plugin auto-add (Trakt/Listrr/mdblist), or an item created via
    /// `discoverItem`, which never creates an `item_requests` row.
    ///
    /// A Seerr-originated request collapses to the fixed label `"Seerr"`
    /// rather than the specific Seerr user who asked for it — that identity
    /// lives in Seerr's own UI, not duplicated here. `item_requests.requested_by`
    /// doubles as that Seerr-requester email *and*, for a request made
    /// directly through riven's own `requestMovie`/`requestShow`/`addItem`
    /// mutations, the riven username that called them — `external_request_id`
    /// (set only by Seerr) is what tells the two apart.
    async fn added_by(
        &self,
        ctx: &async_graphql::Context<'_>,
    ) -> async_graphql::Result<Option<String>> {
        let Some(item_request_id) = self.item_request_id else {
            return Ok(None);
        };
        let db = ctx.data::<sea_orm::DatabaseConnection>()?;
        let request = super::item_requests::Entity::find_by_id(item_request_id)
            .one(db)
            .await?;
        Ok(request.and_then(|request| {
            if request.external_request_id.is_some() {
                Some("Seerr".to_string())
            } else {
                request.requested_by
            }
        }))
    }
}
