//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    async_graphql::SimpleObject,
)]
#[graphql(name = "Stream")]
#[sea_orm(table_name = "streams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub info_hash: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub parsed_data: Option<Json>,
    pub rank: Option<i64>,
    pub file_size_bytes: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub magnet: String,
    pub created_at: DateTimeUtc,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::filesystem_entries::Entity")]
    FilesystemEntries,
    #[sea_orm(has_many = "super::media_item_blacklisted_streams::Entity")]
    MediaItemBlacklistedStreams,
    #[sea_orm(has_many = "super::media_item_streams::Entity")]
    MediaItemStreams,
    #[sea_orm(has_many = "super::media_items::Entity")]
    MediaItems,
}

impl Related<super::filesystem_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FilesystemEntries.def()
    }
}

impl Related<super::media_item_blacklisted_streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItemBlacklistedStreams.def()
    }
}

impl Related<super::media_item_streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItemStreams.def()
    }
}

impl Related<super::media_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
